{% set name = "ibmcloudant" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ibmcloudant-{{ version }}.tar.gz
  sha256: 43cd780ac3b0e7c03be016a97aa96809a5551e78d92f22c7c5913375da93353b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.9,<4
    - pip
  run:
    - python >={{ python_min }}
    - ibm-cloud-sdk-core ==3.24.2
    - requests >=2.32.4,<3.0.0
    - python-dateutil >=2.5.3,<3.0.0
    - pyjwt >=2.0.1,<3.0.0

test:
  imports:
    - ibmcloudant
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/IBM/cloudant-python-sdk
  summary: Python client library for IBM Cloudant
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/IBM/cloudant-python-sdk
  doc_url: https://github.com/IBM/cloudant-python-sdk/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
