{% set name = "ibmcloudant" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ibmcloudant-{{ version }}.tar.gz
  sha256: 35444d4dedb028dbe61f69e359971ead99feb0bbef76d3fbd00addc466e99255

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.9,<4
    - pip
  run:
    - python >=3.8
    - ibm-cloud-sdk-core ==3.21.0
    - requests >=2.32.2,<3.0.0
    - python-dateutil >=2.5.3,<3.0.0
    - pyjwt >=2.0.1,<3.0.0

test:
  imports:
    - ibmcloudant
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/cloudant-python-sdk
  summary: Python client library for IBM Cloudant
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/IBM/cloudant-python-sdk
  doc_url: https://github.com/IBM/cloudant-python-sdk/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
